-- AlterTable
ALTER TABLE "Tender" ADD COLUMN "onlineLink" TEXT;
ALTER TABLE "Tender" ADD COLUMN "bidDecision" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "Tender" ADD COLUMN "documentPrepared" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Tender" ADD COLUMN "bidSubmitted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Tender" ADD COLUMN "quotedRate" DOUBLE PRECISION;
ALTER TABLE "Tender" ADD COLUMN "actualTenderCost" DOUBLE PRECISION;
ALTER TABLE "Tender" ADD COLUMN "tenderExpense" DOUBLE PRECISION;
ALTER TABLE "Tender" ADD COLUMN "resultStatus" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "Tender" ADD COLUMN "workCompleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Tender" ADD COLUMN "workDoneCertificate" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Tender" ADD COLUMN "completionDate" TIMESTAMP(3);
ALTER TABLE "Tender" ADD COLUMN "notes" TEXT;
